"""create_advisories_table

Revision ID: ae512c553e2e
Revises: 405528957632
Create Date: 2026-09-06 17:10:45.705106+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae512c553e2e'
down_revision: Union[str, None] = '405528957632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('risk_type', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('preventive_actions', sa.JSON(), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('time_window', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisories_created_at'), 'advisories', ['created_at'], unique=False)
    op.create_index(op.f('ix_advisories_farm_id'), 'advisories', ['farm_id'], unique=False)
    op.create_index(op.f('ix_advisories_id'), 'advisories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advisories_id'), table_name='advisories')
    op.drop_index(op.f('ix_advisories_farm_id'), table_name='advisories')
    op.drop_index(op.f('ix_advisories_created_at'), table_name='advisories')
    op.drop_table('advisories')
    # ### end Alembic commands ###
